terraform {
  # All configuration (bucket, key, region, use_lockfile)
  # is supplied at runtime via backend.hcl, generated by the CI/CD workflow.
  # For local runs: terraform init -backend-config=backend.hcl
  backend "s3" {}
}
